# MANAGING A DJANGO WEBAPP WITH Docker-Compose
#
# When starting a new project: 
#	- Create a new working directory and add a 'volumes' directive below to mount it over /opt/django_project
#	- Copy this docker-compose file into your new working directory and 'docker-compose up',
#	- Run the setup project command from below, 'docker-compose up' again, check django is running OK in a browser
#
# COMMANDS:
#	Start/restart a server:
#		docker-compose up -d
#	Setup project/directory structure (new projects):
# 		docker-compose run webapp django-admin.py startproject django_project /opt/django_project
#	Initialise database (configure settings.py first):
#		docker-compose run webapp python3.4 /opt/django_project/manage.py syncdb
#	Initialise app:
#		docker-compose run webapp python3.4 /opt/django_project/manage.py startapp [app_label]
webapp:
  build: .
  volumes:
    - .:/opt/django_project
    - ./static:/opt/django_project/webapp/static
  ports:
    - "80:80"

selenium:
  image: selenium/standalone-firefox
  ports:
    - "4444:4444"